version: '3.8'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./auth/:/opt/app/auth"
      - "./routes/:/opt/app/routes"
      - "./database/:/opt/app/database"
    ports:
      - "5000:5000"
    tty: true
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
